version: "3.9"

services:

  database:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  backend:
    build: backend
    depends_on:
      - database
    ports:
      - 5000:5000

  frontend:
    build: frontend
    depends_on:
      - database
      - backend
    ports:
      - 3000:80
